Miniconda-installer:
    repository: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

QCG-PilotJob:
    repository: https://github.com/vecma-project/QCG-PilotJob.git
    name: QCGPilotManager
    version: 0.6.2
    additional_dependencies:
        - pandas
        - numpy
        - pytest
        - scipy
        - mpi4py
        - cython

packages:
    - matplotlib
