#Anonymous cloning, publicly available
FabMD:
  repository: https://github.com/UCL-CCS/FabMD.git

FabFlee:
  repository: https://github.com/djgroen/FabFlee.git

FabParticleDA:
  repository: https://github.com/djgroen/FabParticleDA.git

FabDummy:
  repository: https://github.com/djgroen/FabDummy.git

FabCannonSim:
  repository: https://github.com/arabnejad/FabCannonsim.git

FabMaMiCo:
  repository: https://github.com/HSU-HPC/FabMaMiCo.git

FabUQCampaign:
  repository: https://github.com/wedeling/FabUQCampaign.git
  
FabChemShell:
  repository: https://github.com/gh3orghiu/FabChemShell.git

FabSMD:
  repository: https://github.com/potterton48/FabSMD.git

#Collaborator status required (as a precaution, as this is in development)
FabMUSCLE:
  repository: https://github.com/djgroen/FabMUSCLE.git

FabProfile:
  repository: https://github.com/NicolasMonnier/FabProfile.git

fabmogp:
  repository: https://github.com/edaub/fabmogp

FabCovid19:
  repository: https://github.com/djgroen/FabCovid19

FabCovidsim:
  repository: https://github.com/arabnejad/FabCovidsim

FabAlya:
  repository: https://github.com/alfonsostg/FabAlya

FabMPS:
  repository: https://github.com/goghino/FabMPS.git
  
FabNEPTUNE:
  repository: https://github.com/UCL-CCS/FabNEPTUNE
  
FabSCEMa:
  repository: https://github.com/UCL-CCS/FabSCEMa

FabDynamics:
  repository: https://github.com/arindamsaha1507/FabDynamics

FabABMCPP:
  repository: https://github.com/shakir507/FabABMCPP
  
FabEco:
  repository: https://github.com/arindamsaha1507/FabEco
  
FabOasis:
  repository: https://github.com/arindamsaha1507/FabOasis

FabNESO:
  repository: https://github.com/UCL/FabNESO

FabGPDR:
  repository: ...
